---
# Config settings for apicrud.service_config
appname: Media
# To disable migration, uncomment these two lines
# db_migrate_enable: false
# db_schema_maxtime: 0
db_schemas: [ apicrud, media ]
service_name: media
thumbnail_tiny: 50
